// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toggler.Infrastructure.Repositories;

namespace Toggler.Infrastructure.Migrations
{
    [DbContext(typeof(TogglerContext))]
    [Migration("20180723123919_Intialize DB")]
    partial class IntializeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Toggler.Domain.Entities.ServiceToggle", b =>
                {
                    b.Property<string>("UniqueId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsEnabled");

                    b.Property<bool>("IsServiceExcluded");

                    b.Property<string>("ServiceDescription");

                    b.Property<string>("ServiceName");

                    b.Property<string>("ServiceVersion");

                    b.Property<string>("ToggleDescription");

                    b.Property<string>("ToggleName");

                    b.Property<int>("ToggleType");

                    b.HasKey("UniqueId");

                    b.ToTable("ServiceToggles");
                });

            modelBuilder.Entity("Toggler.Domain.Entities.Toggle", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("ToggleType");

                    b.HasKey("Name");

                    b.ToTable("Toggles");
                });
#pragma warning restore 612, 618
        }
    }
}
